[package]
name = "fakehub"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
git2 = "0.20.0"
openssl = { version = "0.10", features = ["vendored"] }
rand = "0.9.0"
