name: Release FakeHub

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate version tag
        id: tag
        run: |
          echo "TAG=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}

      - name: Build and Release
        uses: lxl66566/rust-simple-release@v0.2.3
        with:
          targets: >
            x86_64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
            x86_64-pc-windows-msvc,
            x86_64-apple-darwin,
            aarch64-unknown-linux-gnu,
            aarch64-apple-darwin
