name: Release FakeHub MultiOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build for all platforms
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64

      - name: Generate version
        id: version
        run: |
          echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build for all platforms
        run: |
          # Build for Linux
          cargo build --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/fakehub ./fakehub-linux
          
          # Build for macOS
          cargo build --release --target x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/fakehub ./fakehub-macos
          
          # Build for Windows
          cargo build --release --target x86_64-pc-windows-msvc
          cp target/x86_64-pc-windows-msvc/release/fakehub.exe ./fakehub-windows.exe

      - name: Create archives and checksums
        run: |
          # Create archives
          tar -czf fakehub-linux.tar.gz fakehub-linux
          tar -czf fakehub-macos.tar.gz fakehub-macos
          zip fakehub-windows.zip fakehub-windows.exe
          
          # Generate individual checksums for binaries
          sha256sum fakehub-linux > fakehub-linux.sha256
          sha256sum fakehub-macos > fakehub-macos.sha256
          sha256sum fakehub-windows.exe > fakehub-windows.exe.sha256
          
          # Generate individual checksums for archives
          sha256sum fakehub-linux.tar.gz > fakehub-linux.tar.gz.sha256
          sha256sum fakehub-macos.tar.gz > fakehub-macos.tar.gz.sha256
          sha256sum fakehub-windows.zip > fakehub-windows.zip.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            fakehub-linux
            fakehub-macos
            fakehub-windows.exe
            fakehub-linux.tar.gz
            fakehub-macos.tar.gz
            fakehub-windows.zip
            fakehub-linux.sha256
            fakehub-macos.sha256
            fakehub-windows.exe.sha256
            fakehub-linux.tar.gz.sha256
            fakehub-macos.tar.gz.sha256
            fakehub-windows.zip.sha256